version: '3'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - published: 5432
        target: 5432
    networks:
      - db-back

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
    networks:
      - db-back

  greenhub:
    build:
      dockerfile: Dockerfile
    image: greenhub
    ports:
      - published: 8080
        target: 8080
    depends_on:
      - postgres
    environment:
      - "JAVA_OPTS="
    networks:
      - db-back

volumes:
  minio-data:
  postgres-data:

networks:
  db-back:
