server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ihseeranegubza
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/grnhub_db
    username: grnhub_db_user
    password: $2a$12$4UVus2Y1sf8k2HYzO47qyuDidwlUmeLb.ZE8Hh7qDxvcnVe8uT.HO #grnhub_db_password Bcrypt12
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 6h
minio:
  bucket: images
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin
  image:
    defaultImagePath: default.png
    defaultImageName: default.png
    activeImagePath: active.png
    activeImageName: active.png
    bicycleImagePath: bicycle.png
    bicycleImageName: bicycle.png
    veganImagePath: vegan.png
    veganImageName: vegan.png
    volonterImagePath: volonter.png
    volonterImageName: volonter.png
    zhivotniImagePath: zhivotni.png
    zhivotniImageName: zhivotni.png
logging:
  level:
    org:
      springframework:
        web: DEBUG
